version: "3"
services:
    postgres-db:
        image: postgres:13.2-alpine
        container_name: pg_tst        
        environment:
            POSTGRES_DB: your_db
            POSTGRES_USER: your_user
            POSTGRES_PASSWORD: your_password  
            TZ: Asia/Taipei                  
        volumes:
            - postgres-db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"           
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pg_admin        
        environment:
            PGADMIN_DEFAULT_EMAIL: your_email
            PGADMIN_DEFAULT_PASSWORD: your_password
            PGADMIN_LISTEN_PORT: 80
            TZ: Asia/Taipei
        ports:
            - "80:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin        
    backend-fastapi:
        build:
            context: .
            dockerfile: Dockerfile_fastapi
        container_name: fastapi_tst 
        image: img_fastapi_01  
        environment:
            TZ: Asia/Taipei             
        ports:
            - "5001:80"
        depends_on:
            - postgres-db    
    frendend-coremvc:
        build: 
            context: .
            dockerfile: Dockerfile_coremvc 
        container_name: coremvc_01
        image: img_coremvc_01 
        environment:
            TZ: Asia/Taipei        
        ports:
            - "8000:8080"  
        depends_on:
            - backend-fastapi                    
volumes:
    postgres-db-data:
    pgadmin-data:   