FROM python:3.8
WORKDIR /code

COPY DemoFastApi/requirements.txt /code/requirements.txt
COPY DemoFastApi/models /code/models 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY DemoFastApi/get_data.py /code
COPY DemoFastApi/main.py /code
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]